export const PARENT_CATEGORIES = [
  { name: "Araçlar", slug: "araclar", icon: "🚗" },
  { name: "Emlak", slug: "emlak", icon: "🏠" },
  { name: "Elektronik", slug: "elektronik", icon: "📱" },
  { name: "Giyim", slug: "giyim", icon: "👗" },
  { name: "Ev & Yaşam", slug: "ev-yasam", icon: "🛋️" },
  { name: "Oyun & Hobi", slug: "oyun-hobi", icon: "🎮" },
  { name: "Bisiklet", slug: "bisiklet", icon: "🚲" },
  { name: "Kitap & Müzik", slug: "kitap-muzik", icon: "📚" },
  { name: "Spor", slug: "spor", icon: "⚽" },
  { name: "Özel Ders", slug: "ozel-ders", icon: "📖" },
  { name: "İş İlanları", slug: "is-ilanlari", icon: "💼" },
  { name: "Tarım & Bahçe", slug: "tarim-bahce", icon: "🌱" },
  { name: "Kozmetik & Bakım", slug: "kozmetik", icon: "💄" },
  { name: "Yiyecek & İçecek", slug: "yiyecek", icon: "🍕" },
  { name: "Hizmetler", slug: "hizmetler", icon: "🔧" },
  { name: "Nakliyat", slug: "nakliyat", icon: "🚚" },
  { name: "Diğer", slug: "diger", icon: "📦" },
];

export const SUBCATEGORIES = {
  araclar: [
    { name: "Otomobil", slug: "otomobil" },
    { name: "Arazi, SUV & Pickup", slug: "arazi-suv" },
    { name: "Motosiklet", slug: "motosiklet" },
    { name: "Minivan & Panelvan", slug: "minivan" },
    { name: "Ticari Araç", slug: "ticari-arac" },
  ],
  emlak: [
    { name: "Konut", slug: "konut" },
    { name: "İş Yeri", slug: "is-yeri" },
    { name: "Arsa", slug: "arsa" },
    { name: "Devremülk", slug: "devremulk" },
    { name: "Turistik Tesis", slug: "turistik-tesis" },
  ],
  elektronik: [
    { name: "Cep Telefonu", slug: "telefon" },
    { name: "Bilgisayar", slug: "bilgisayar" },
    { name: "Tablet", slug: "tablet" },
    { name: "TV & Ses Sistemleri", slug: "tv-ses" },
    { name: "Fotoğraf & Kamera", slug: "foto-kamera" },
    { name: "Oyun Konsolu", slug: "konsol" },
  ],
  giyim: [
    { name: "Kadın", slug: "kadin-giyim" },
    { name: "Erkek", slug: "erkek-giyim" },
    { name: "Çocuk", slug: "cocuk-giyim" },
    { name: "Ayakkabı", slug: "ayakkabi" },
    { name: "Çanta & Aksesuar", slug: "aksesuar" },
  ],
  "ev-yasam": [
    { name: "Mobilya", slug: "mobilya" },
    { name: "Dekorasyon", slug: "dekorasyon" },
    { name: "Mutfak", slug: "mutfak" },
    { name: "Beyaz Eşya", slug: "beyaz-esya" },
    { name: "Bahçe & Yapı", slug: "bahce" },
  ],
  "oyun-hobi": [
    { name: "Konsol Oyunları", slug: "konsol-oyun" },
    { name: "PC Oyunları", slug: "pc-oyun" },
    { name: "Koleksiyon", slug: "koleksiyon" },
    { name: "Müzik Aletleri", slug: "muzik-aletleri" },
    { name: "Model & Maket", slug: "model-maket" },
  ],
  bisiklet: [
    { name: "Dağ Bisikleti", slug: "dag-bisiklet" },
    { name: "Yol Bisikleti", slug: "yol-bisiklet" },
    { name: "Şehir & Gezi", slug: "sehir-bisiklet" },
    { name: "Elektrikli Bisiklet", slug: "elektrikli-bisiklet" },
  ],
  spor: [
    { name: "Fitness", slug: "fitness" },
    { name: "Outdoor", slug: "outdoor" },
    { name: "Takım Sporları", slug: "takim-spor" },
    { name: "Su Sporları", slug: "su-spor" },
  ],
  "kitap-muzik": [
    { name: "Kitap", slug: "kitap" },
    { name: "Dergi", slug: "dergi" },
    { name: "Plak & CD", slug: "plak-cd" },
    { name: "Film", slug: "film" },
  ],
  "ozel-ders": [
    { name: "Yabancı Dil", slug: "yabanci-dil" },
    { name: "Matematik & Fen", slug: "matematik-fen" },
    { name: "Müzik", slug: "muzik-ders" },
    { name: "Spor & Dans", slug: "spor-dans" },
  ],
};
